var xui;
(function(){var z;xui=function(d){d=d||document;return this.find(d)};idExpr=/^#([\w-]+)$/;xui.extend=function(d){var f=this.prototype;for(var h in d||{})f[h]=d[h];return f};xui.prototype={elements:[],find:function(d){var f=[],h=d.length,j,m,l,q;if(typeof d=="string"&&idExpr.test(d)){this.elements.push(document.getelementsById(d));return this}for(l=0;l<h;l++)if(typeof d[l]=="string"){j=document.querySelectorAll?document.querySelectorAll(d[l]):Sizzle(d[l]);m=j.length;for(q=0;q<m;q++)f.push(j[q])}else if(d[l]instanceof Array)for(var r=
0;r<d[l].length;r++){j=document.querySelectorAll?document.querySelectorAll(d[l][r]):Sizzle(d[l][r]);m=j.length;for(q=0;q<m;q++)f.push(j[q])}else f.push(d[l]);this.elements=this.elements.concat(this.reduce(f));return this},reduce:function(d,f){var h=[],j,m=d.length;for(j=0;j<m;j++)h.indexOf(d[j],0,f)<0&&h.push(d[j]);return h},removex:function(d,f,h){h=d.slice((h||f)+1||d.length);d.length=f<0?d.length+f:f;return d.push.apply(d,h)},has:function(d){var f=[];this.each(function(h){x$(d).each(function(j){j==
h&&f.push(h)})});this.elements=f;return this},not:function(d){for(var f=this.elements,h=0;h<f.length;h++)x$(d).each(function(j){if(f[h]==j)this.elements=this.removex(f,f.indexOf(f[h]))});return this},add:function(d){this.find([d]);this.elements=this.reduce(this.elements);return this},first:function(){return this.get(0)},get:function(d){return this.elements[d]},eq:function(d,f){f=f?f+1:d+1;this.elements=this.elements.slice(d,f);return this},size:function(){return this.elements.length},each:function(d){for(var f=
0,h=this.elements.length;f<h;++f)if(d.call(this,this.elements[f])===false)break;return this}};var u=[];(function(){function d(a){for(var b="",c,e=0;a[e];e++){c=a[e];if(c.nodeType===3||c.nodeType===4)b+=c.nodeValue;else if(c.nodeType!==8)b+=d(c.childNodes)}return b}function f(a,b,c,e,i,g){i=0;for(var p=e.length;i<p;i++){var o=e[i];if(o){o=o[a];for(var s=false;o;){if(o.sizcache===c){s=e[o.sizset];break}if(o.nodeType===1&&!g){o.sizcache=c;o.sizset=i}if(o.nodeName.toLowerCase()===b){s=o;break}o=o[a]}e[i]=
s}}}function h(a,b,c,e,i,g){i=0;for(var p=e.length;i<p;i++){var o=e[i];if(o){o=o[a];for(var s=false;o;){if(o.sizcache===c){s=e[o.sizset];break}if(o.nodeType===1){if(!g){o.sizcache=c;o.sizset=i}if(typeof b!=="string"){if(o===b){s=true;break}}else if(n.filter(b,[o]).length>0){s=o;break}}o=o[a]}e[i]=s}}}var j=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|['"][^'"]*['"]|[^[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,m=0,l=Object.prototype.toString,q=false,r=true;[0,0].sort(function(){r=
false;return 0});var n=function(a,b,c,e){c=c||[];var i=b=b||document;if(b.nodeType!==1&&b.nodeType!==9)return[];if(!a||typeof a!=="string")return c;for(var g=[],p,o,s,G,B=true,F=A(b),C=a;(j.exec(""),p=j.exec(C))!==null;){C=p[3];g.push(p[1]);if(p[2]){G=p[3];break}}if(g.length>1&&t.exec(a))if(g.length===2&&k.relative[g[0]])o=H(g[0]+g[1],b);else for(o=k.relative[g[0]]?[b]:n(g.shift(),b);g.length;){a=g.shift();if(k.relative[a])a+=g.shift();o=H(a,o)}else{if(!e&&g.length>1&&b.nodeType===9&&!F&&k.match.ID.test(g[0])&&
!k.match.ID.test(g[g.length-1])){p=n.find(g.shift(),b,F);b=p.expr?n.filter(p.expr,p.set)[0]:p.set[0]}if(b){p=e?{expr:g.pop(),set:w(e)}:n.find(g.pop(),g.length===1&&(g[0]==="~"||g[0]==="+")&&b.parentNode?b.parentNode:b,F);o=p.expr?n.filter(p.expr,p.set):p.set;if(g.length>0)s=w(o);else B=false;for(;g.length;){var x=g.pop();p=x;if(k.relative[x])p=g.pop();else x="";if(p==null)p=b;k.relative[x](s,p,F)}}else s=[]}s||(s=o);if(!s)throw"Syntax error, unrecognized expression: "+(x||a);if(l.call(s)==="[object Array]")if(B)if(b&&
b.nodeType===1)for(a=0;s[a]!=null;a++){if(s[a]&&(s[a]===true||s[a].nodeType===1&&J(b,s[a])))c.push(o[a])}else for(a=0;s[a]!=null;a++)s[a]&&s[a].nodeType===1&&c.push(o[a]);else c.push.apply(c,s);else w(s,c);if(G){n(G,i,c,e);n.uniqueSort(c)}return c};n.uniqueSort=function(a){if(D){q=r;a.sort(D);if(q)for(var b=1;b<a.length;b++)a[b]===a[b-1]&&a.splice(b--,1)}return a};n.matches=function(a,b){return n(a,null,null,b)};n.find=function(a,b,c){var e,i;if(!a)return[];for(var g=0,p=k.order.length;g<p;g++){var o=
k.order[g];if(i=k.leftMatch[o].exec(a)){var s=i[1];i.splice(1,1);if(s.substr(s.length-1)!=="\\"){i[1]=(i[1]||"").replace(/\\/g,"");e=k.find[o](i,b,c);if(e!=null){a=a.replace(k.match[o],"");break}}}}e||(e=b.getElementsByTagName("*"));return{set:e,expr:a}};n.filter=function(a,b,c,e){for(var i=a,g=[],p=b,o,s,G=b&&b[0]&&A(b[0]);a&&b.length;){for(var B in k.filter)if((o=k.match[B].exec(a))!=null){var F=k.filter[B],C,x;s=false;if(p===g)g=[];if(k.preFilter[B])if(o=k.preFilter[B](o,p,c,g,e,G)){if(o===true)continue}else s=
C=true;if(o)for(var I=0;(x=p[I])!=null;I++)if(x){C=F(x,o,I,p);var L=e^!!C;if(c&&C!=null)if(L)s=true;else p[I]=false;else if(L){g.push(x);s=true}}if(C!==z){c||(p=g);a=a.replace(k.match[B],"");if(!s)return[];break}}if(a===i)if(s==null)throw"Syntax error, unrecognized expression: "+a;else break;i=a}return p};var k=n.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,
TAG:/^((?:[\w\u00c0-\uFFFF\*-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF-]|\\.)+)(?:\((['"]*)((?:\([^\)]+\)|[^\2\(\)]*)+)\2\))?/},leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(a){return a.getAttribute("href")}},relative:{"+":function(a,b){var c=typeof b==="string",e=c&&!/\W/.test(b);c=c&&!e;if(e)b=b.toLowerCase();e=0;for(var i=a.length,
g;e<i;e++)if(g=a[e]){for(;(g=g.previousSibling)&&g.nodeType!==1;);a[e]=c||g&&g.nodeName.toLowerCase()===b?g||false:g===b}c&&n.filter(b,a,true)},">":function(a,b){var c=typeof b==="string";if(c&&!/\W/.test(b)){b=b.toLowerCase();for(var e=0,i=a.length;e<i;e++){var g=a[e];if(g){c=g.parentNode;a[e]=c.nodeName.toLowerCase()===b?c:false}}}else{e=0;for(i=a.length;e<i;e++)if(g=a[e])a[e]=c?g.parentNode:g.parentNode===b;c&&n.filter(b,a,true)}},"":function(a,b,c){var e=m++,i=h;if(typeof b==="string"&&!/\W/.test(b)){var g=
b=b.toLowerCase();i=f}i("parentNode",b,e,a,g,c)},"~":function(a,b,c){var e=m++,i=h;if(typeof b==="string"&&!/\W/.test(b)){var g=b=b.toLowerCase();i=f}i("previousSibling",b,e,a,g,c)}},find:{ID:function(a,b,c){if(typeof b.getElementById!=="undefined"&&!c)return(a=b.getElementById(a[1]))?[a]:[]},NAME:function(a,b){if(typeof b.getElementsByName!=="undefined"){var c=[];b=b.getElementsByName(a[1]);for(var e=0,i=b.length;e<i;e++)b[e].getAttribute("name")===a[1]&&c.push(b[e]);return c.length===0?null:c}},
TAG:function(a,b){return b.getElementsByTagName(a[1])}},preFilter:{CLASS:function(a,b,c,e,i,g){a=" "+a[1].replace(/\\/g,"")+" ";if(g)return a;g=0;for(var p;(p=b[g])!=null;g++)if(p)if(i^(p.className&&(" "+p.className+" ").replace(/[\t\n]/g," ").indexOf(a)>=0))c||e.push(p);else if(c)b[g]=false;return false},ID:function(a){return a[1].replace(/\\/g,"")},TAG:function(a){return a[1].toLowerCase()},CHILD:function(a){if(a[1]==="nth"){var b=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(a[2]==="even"&&"2n"||a[2]==="odd"&&
"2n+1"||!/\D/.test(a[2])&&"0n+"+a[2]||a[2]);a[2]=b[1]+(b[2]||1)-0;a[3]=b[3]-0}a[0]=m++;return a},ATTR:function(a,b,c,e,i,g){b=a[1].replace(/\\/g,"");if(!g&&k.attrMap[b])a[1]=k.attrMap[b];if(a[2]==="~=")a[4]=" "+a[4]+" ";return a},PSEUDO:function(a,b,c,e,i){if(a[1]==="not")if((j.exec(a[3])||"").length>1||/^\w/.test(a[3]))a[3]=n(a[3],null,null,b);else{a=n.filter(a[3],b,c,true^i);c||e.push.apply(e,a);return false}else if(k.match.POS.test(a[0])||k.match.CHILD.test(a[0]))return true;return a},POS:function(a){a.unshift(true);
return a}},filters:{enabled:function(a){return a.disabled===false&&a.type!=="hidden"},disabled:function(a){return a.disabled===true},checked:function(a){return a.checked===true},selected:function(a){return a.selected===true},parent:function(a){return!!a.firstChild},empty:function(a){return!a.firstChild},has:function(a,b,c){return!!n(c[3],a).length},header:function(a){return/h\d/i.test(a.nodeName)},text:function(a){return"text"===a.type},radio:function(a){return"radio"===a.type},checkbox:function(a){return"checkbox"===
a.type},file:function(a){return"file"===a.type},password:function(a){return"password"===a.type},submit:function(a){return"submit"===a.type},image:function(a){return"image"===a.type},reset:function(a){return"reset"===a.type},button:function(a){return"button"===a.type||a.nodeName.toLowerCase()==="button"},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)}},setFilters:{first:function(a,b){return b===0},last:function(a,b,c,e){return b===e.length-1},even:function(a,b){return b%2===
0},odd:function(a,b){return b%2===1},lt:function(a,b,c){return b<c[3]-0},gt:function(a,b,c){return b>c[3]-0},nth:function(a,b,c){return c[3]-0===b},eq:function(a,b,c){return c[3]-0===b}},filter:{PSEUDO:function(a,b,c,e){var i=b[1],g=k.filters[i];if(g)return g(a,c,b,e);else if(i==="contains")return(a.textContent||a.innerText||d([a])||"").indexOf(b[3])>=0;else if(i==="not"){b=b[3];c=0;for(e=b.length;c<e;c++)if(b[c]===a)return false;return true}else throw"Syntax error, unrecognized expression: "+i;},
CHILD:function(a,b){var c=b[1],e=a;switch(c){case "only":case "first":for(;e=e.previousSibling;)if(e.nodeType===1)return false;if(c==="first")return true;e=a;case "last":for(;e=e.nextSibling;)if(e.nodeType===1)return false;return true;case "nth":c=b[2];var i=b[3];if(c===1&&i===0)return true;b=b[0];var g=a.parentNode;if(g&&(g.sizcache!==b||!a.nodeIndex)){var p=0;for(e=g.firstChild;e;e=e.nextSibling)if(e.nodeType===1)e.nodeIndex=++p;g.sizcache=b}a=a.nodeIndex-i;return c===0?a===0:a%c===0&&a/c>=0}},
ID:function(a,b){return a.nodeType===1&&a.getAttribute("id")===b},TAG:function(a,b){return b==="*"&&a.nodeType===1||a.nodeName.toLowerCase()===b},CLASS:function(a,b){return(" "+(a.className||a.getAttribute("class"))+" ").indexOf(b)>-1},ATTR:function(a,b){var c=b[1];a=k.attrHandle[c]?k.attrHandle[c](a):a[c]!=null?a[c]:a.getAttribute(c);c=a+"";var e=b[2];b=b[4];return a==null?e==="!=":e==="="?c===b:e==="*="?c.indexOf(b)>=0:e==="~="?(" "+c+" ").indexOf(b)>=0:!b?c&&a!==false:e==="!="?c!==b:e==="^="?c.indexOf(b)===
0:e==="$="?c.substr(c.length-b.length)===b:e==="|="?c===b||c.substr(0,b.length+1)===b+"-":false},POS:function(a,b,c,e){var i=k.setFilters[b[2]];if(i)return i(a,c,b,e)}}},t=k.match.POS;for(var v in k.match){k.match[v]=new RegExp(k.match[v].source+/(?![^\[]*\])(?![^\(]*\))/.source);k.leftMatch[v]=new RegExp(/(^(?:.|\r|\n)*?)/.source+k.match[v].source)}var w=function(a,b){a=Array.prototype.slice.call(a,0);if(b){b.push.apply(b,a);return b}return a};try{Array.prototype.slice.call(document.documentElement.childNodes,
0)}catch(K){w=function(a,b){b=b||[];if(l.call(a)==="[object Array]")Array.prototype.push.apply(b,a);else if(typeof a.length==="number")for(var c=0,e=a.length;c<e;c++)b.push(a[c]);else for(c=0;a[c];c++)b.push(a[c]);return b}}var D;if(document.documentElement.compareDocumentPosition)D=function(a,b){if(!a.compareDocumentPosition||!b.compareDocumentPosition){if(a==b)q=true;return a.compareDocumentPosition?-1:1}a=a.compareDocumentPosition(b)&4?-1:a===b?0:1;if(a===0)q=true;return a};else if("sourceIndex"in
document.documentElement)D=function(a,b){if(!a.sourceIndex||!b.sourceIndex){if(a==b)q=true;return a.sourceIndex?-1:1}a=a.sourceIndex-b.sourceIndex;if(a===0)q=true;return a};else if(document.createRange)D=function(a,b){if(!a.ownerDocument||!b.ownerDocument){if(a==b)q=true;return a.ownerDocument?-1:1}var c=a.ownerDocument.createRange(),e=b.ownerDocument.createRange();c.setStart(a,0);c.setEnd(a,0);e.setStart(b,0);e.setEnd(b,0);a=c.compareBoundaryPoints(Range.START_TO_END,e);if(a===0)q=true;return a};
(function(){var a=document.createElement("div"),b="script"+(new Date).getTime();a.innerHTML="<a name='"+b+"'/>";var c=document.documentElement;c.insertBefore(a,c.firstChild);if(document.getElementById(b)){k.find.ID=function(e,i,g){if(typeof i.getElementById!=="undefined"&&!g)return(i=i.getElementById(e[1]))?i.id===e[1]||typeof i.getAttributeNode!=="undefined"&&i.getAttributeNode("id").nodeValue===e[1]?[i]:z:[]};k.filter.ID=function(e,i){var g=typeof e.getAttributeNode!=="undefined"&&e.getAttributeNode("id");
return e.nodeType===1&&g&&g.nodeValue===i}}c.removeChild(a);c=a=null})();(function(){var a=document.createElement("div");a.appendChild(document.createComment(""));if(a.getElementsByTagName("*").length>0)k.find.TAG=function(b,c){c=c.getElementsByTagName(b[1]);if(b[1]==="*"){b=[];for(var e=0;c[e];e++)c[e].nodeType===1&&b.push(c[e]);c=b}return c};a.innerHTML="<a href='#'></a>";if(a.firstChild&&typeof a.firstChild.getAttribute!=="undefined"&&a.firstChild.getAttribute("href")!=="#")k.attrHandle.href=function(b){return b.getAttribute("href",
2)};a=null})();document.querySelectorAll&&function(){var a=n,b=document.createElement("div");b.innerHTML="<p class='TEST'></p>";if(!(b.querySelectorAll&&b.querySelectorAll(".TEST").length===0)){n=function(e,i,g,p){i=i||document;if(!p&&i.nodeType===9&&!A(i))try{return w(i.querySelectorAll(e),g)}catch(o){}return a(e,i,g,p)};for(var c in a)n[c]=a[c];b=null}}();(function(){var a=document.createElement("div");a.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!a.getElementsByClassName||
a.getElementsByClassName("e").length===0)){a.lastChild.className="e";if(a.getElementsByClassName("e").length!==1){k.order.splice(1,0,"CLASS");k.find.CLASS=function(b,c,e){if(typeof c.getElementsByClassName!=="undefined"&&!e)return c.getElementsByClassName(b[1])};a=null}}})();var J=document.compareDocumentPosition?function(a,b){return a.compareDocumentPosition(b)&16}:function(a,b){return a!==b&&(a.contains?a.contains(b):true)},A=function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?a.nodeName!==
"HTML":false},H=function(a,b){var c=[],e="",i;for(b=b.nodeType?[b]:b;i=k.match.PSEUDO.exec(a);){e+=i[0];a=a.replace(k.match.PSEUDO,"")}a=k.relative[a]?a+"*":a;i=0;for(var g=b.length;i<g;i++)n(a,b[i],c);return n.filter(e,c)};window.Sizzle=n})();u.push({inner:function(d){return this.html("inner",d)},outer:function(d){return this.html("outer",d)},top:function(d){return this.html("top",d)},bottom:function(d){return this.html("bottom",d)},remove:function(){return this.html("remove")},before:function(d){return this.html("before",
d)},after:function(d){return this.html("after",d)},html:function(d,f){var h=function(m){if(m.firstChild===null)switch(m.tagName){case "UL":return"LI";case "DL":return"DT";case "TR":return"TD";default:return m.tagName}return m.firstChild.tagName},j=function(m,l){var q={},r=/^<([A-Z][A-Z0-9]*)([^>]*)>(.*)<\/\1>/i;if(r.test(m)){result=r.exec(m);l=result[1];if(result[2]!==""){m=result[2].split(/([A-Z]*\s*=\s*['|"][A-Z0-9:;#\s]*['|"])/i);for(r=0;r<m.length;r++){var n=m[r].replace(/^\s*|\s*$/g,"");if(n!==
""&&n!==" "){n=n.split("=");q[n[0]]=n[1].replace(/(["']?)/g,"")}}}m=result[3]}l=document.createElement(l);for(var k in q){r=document.createAttribute(k);r.nodeValue=q[k];l.setAttributeNode(r)}l.innerHTML=m;return l};this.clean();if(arguments.length==0)return this.elements[0].innerHTML;if(arguments.length==1&&arguments[0]!="remove"){f=d;d="inner"}this.each(function(m){switch(d){case "inner":if(typeof f=="string"){m.innerHTML=f;m=m.getElementsByTagName("SCRIPT");for(var l=m.length,q=0;q<l;q++)eval(m[q].text)}else{m.innerHTML=
"";m.appendChild(f)}break;case "outer":if(typeof f=="string")f=j(f,h(m));m.parentNode.replaceChild(f,m);break;case "top":if(typeof f=="string")f=j(f,h(m));m.insertBefore(f,m.firstChild);break;case "bottom":if(typeof f=="string")f=j(f,h(m));m.insertBefore(f,null);break;case "remove":l=m.parentNode;l.removeChild(m);break;case "before":l=m.parentNode;if(typeof f=="string")f=j(f,h(l));l.insertBefore(f,m);break;case "after":l=m.parentNode;if(typeof f=="string")f=j(f,h(l));l.insertBefore(f,m.nextSibling);
break}});return this},clean:function(){var d=/\S/;this.each(function(f){for(var h=f.firstChild,j=-1;h;){var m=h.nextSibling;if(h.nodeType==3&&!d.test(h.nodeValue))f.removeChild(h);else h.nodeIndex=++j;h=m}});return this},attr:function(d,f){if(arguments.length==2){this.each(function(j){j.setAttribute(d,f)});return this}else{var h=[];this.each(function(j){j.getAttribute(d)!=null&&h.push(j.getAttribute(d))});return h}}});u.push({click:function(d){return this.on("click",d)},load:function(d){return this.on("load",
d)},submit:function(d){return this.on("submit",d)},touchstart:function(d){return this.on("touchstart",d)},touchmove:function(d){return this.on("touchmove",d)},touchend:function(d){return this.on("touchend",d)},touchcancel:function(d){return this.on("touchcancel",d)},gesturestart:function(d){return this.on("gesturestart",d)},gesturechange:function(d){return this.on("gesturechange",d)},gestureend:function(d){return this.on("gestureend",d)},orientationchange:function(d){return this.on("orientationchange",
d)},on:function(d,f){var h=function(j){window.addEventListener&&j.addEventListener(d,f,false)};this.each(function(j){h(j)});return this}});u.push({setStyle:function(d,f){this.each(function(h){h.style[d]=f});return this},getStyle:function(d,f){var h=function(j,m){return document.defaultView.getComputedStyle(j,"").getPropertyValue(m)};if(f===z)return h(this.first(),d);this.each(function(j){f(h(j,d))});return this},addClass:function(d){var f=this,h=function(j,m){return f.getClassRegEx(m).test(j.className)};
this.each(function(j){if(h(j,d)===false)j.className+=" "+d});return this},hasClass:function(d,f){var h=this;if(f===z&&this.elements.length==1)return this.getClassRegEx(d).test(h.first().className);this.each(function(j){h.getClassRegEx(d).test(j.className)==true&&f(j)});return this},removeClass:function(d){if(d===z)this.each(function(h){h.className=""});else{var f=this.getClassRegEx(d);this.each(function(h){h.className=h.className.replace(f," ")})}return this},css:function(d){var f=this;this.each(function(){for(var h in d)f.setStyle(h,
d[h])});return this||f},reClassNameCache:{},getClassRegEx:function(d){var f=this.reClassNameCache[d];if(!f){f=new RegExp("(?:^|\\s+)"+d+"(?:\\s+|$)");this.reClassNameCache[d]=f}return f}});u.push({tween:function(d,f){this.each(function(h){emile(h,d,f)});return this}});u.push({xhr:function(d,f,h){if(!/^inner|outer|top|bottom|before|after$/.test(d)){h=f;f=d;d="inner"}var j=h;if(typeof h=="function"){j={};j.callback=h}h||(j={});if(this.first().tagName=="FORM"){j.callback=f;f=this.first().action;j.data=
this._toQueryString(this.first());j.method=this.first().method}var m=this;h=new XMLHttpRequest;var l=j.method||"get",q=j.async||false,r=j.data||null;h.queryString=r;if(j.headers)for(var n=0;n<j.headers.length;n++)h.setRequestHeader(j.headers[n].name,j.headers[n].value);h.open(l,f,q);h.setRequestHeader("X-Requested-With","XMLHttpRequest");h.onload=j.callback!=null?j.callback:function(){m.html(d,this.responseText)};h.send(r);return this}});for(var E=0,y=u.length;E<y;E++)xui.extend(u[E]);window.x$=function(){return new xui(arguments)}})();
(function(z,u){function E(l,q,r){return(l+(q-l)*r).toFixed(3)}function y(l,q,r){return l.substr(q,r||1)}function d(l,q,r){for(var n=2,k,t,v=[],w=[];k=3,t=arguments[n-1],n--;)if(y(t,0)=="r")for(t=t.match(/\d+/g);k--;)v.push(~~t[k]);else{if(t.length==4)t="#"+y(t,1)+y(t,1)+y(t,2)+y(t,2)+y(t,3)+y(t,3);for(;k--;)v.push(parseInt(y(t,1+k*2,2),16))}for(;k--;){n=~~(v[k+3]+(v[k]-v[k+3])*r);w.push(n<0?0:n>255?255:n)}return"rgb("+w.join(",")+")"}function f(l){var q=parseFloat(l);l=l.replace(/^[\-\d\.]+/,"");
return isNaN(q)?{v:l,f:d,u:""}:{v:q,f:E,u:l}}function h(l){var q={},r=m.length,n;j.innerHTML='<div style="'+l+'"></div>';for(l=j.childNodes[0].style;r--;)if(n=l[m[r]])q[m[r]]=f(n);return q}var j=document.createElement("div"),m="backgroundColor borderBottomColor borderBottomWidth borderLeftColor borderLeftWidth borderRightColor borderRightWidth borderSpacing borderTopColor borderTopWidth bottom color fontSize fontWeight height left letterSpacing lineHeight marginBottom marginLeft marginRight marginTop maxHeight maxWidth minHeight minWidth opacity outlineColor outlineOffset outlineWidth paddingBottom paddingLeft paddingRight paddingTop right textIndent top width wordSpacing zIndex".split(" ");
u[z]=function(l,q,r){l=typeof l=="string"?document.getElementById(l):l;r=r||{};var n=h(q);q=l.currentStyle?l.currentStyle:getComputedStyle(l,null);var k,t={},v=+new Date,w=r.duration||200,K=v+w,D,J=r.easing||function(A){return-Math.cos(A*Math.PI)/2+0.5};for(k in n)t[k]=f(q[k]);D=setInterval(function(){var A=+new Date,H=A>K?1:(A-v)/w;for(k in n)l.style[k]=n[k].f(t[k].v,n[k].v,J(H))+n[k].u;if(A>K){clearInterval(D);r.after&&r.after()}},10)}})("emile",this);
Array.prototype.indexOf=function(z,u){var E=this.length;for(u=u<0?Math.max(0,E+u):u||0;u<E;u++)if(this[u]===z)return u;return-1};
